# Generated by Django 5.0.14 on 2026-08-16 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pseudo', models.CharField(help_text='Pseudo unique visible par les autres membres (3–50 caractères).', max_length=50, unique=True, verbose_name='Pseudo')),
                ('email', models.EmailField(help_text='Adresse email utilisée pour la connexion.', max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, default='', help_text='Facultatif. Utilisé pour personnaliser les emails.', max_length=150, verbose_name='Prénom')),
                ('is_active', models.BooleanField(default=True, help_text="Désactivez ce compte pour interdire la connexion sans supprimer l'utilisateur.", verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Permet l'accès à l'interface d'administration Django.", verbose_name='Accès administration')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
