import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'content');
const enDir = path.join(root, 'en', 'apprendre-arabe');
const arDir = path.join(root, 'ar', 'apprendre-arabe');

function rep(t, pairs) { for (const [a,b] of pairs) t = t.split(a).join(b); return t; }

const commonEn = [
  ['category: "langue-arabe"\n', ''],
  ['✓ Oui', '✓ Yes'], ['✗ Non', '✗ No'], ['⚠ Difficile', '⚠ Difficult'],
  ['## Résumé', '## Summary'], ['maison', 'house'], ['stylo', 'pen'], ['chaise', 'chair'],
  ['livre', 'book'], ['porte', 'door'], ['lumière', 'light'], ['paix', 'peace'],
  ['grand', 'big'], ['beau', 'beautiful'], ['chemin', 'path'], ['âme/esprit', 'soul/spirit'],
  ['muraille', 'wall'], ['il a écrit', 'he wrote'], ['il a étudié', 'he studied'],
  ['écrivain', 'writer'], ['livres', 'books'],
];

const vcEn = [
  ['title: "Voyelles Courtes en Arabe"', 'title: "Short Vowels in Arabic"'],
  ['titleAccent: "La Lecture Invisible"', 'titleAccent: "The Invisible Reading"'],
  ['subtitle: "Les voyelles courtes (harakāt) ne sont PAS des lettres. Ce sont des signes diacritiques qui donnent vie aux consonnes."',
   'subtitle: "Short vowels (harakāt) are NOT letters. They are diacritical marks that bring consonants to life."'],
  ['description: "Comprenez les harakāt : fatha, kasra, damma et sukun. Les voyelles courtes en arabe ne sont PAS des lettres. Guide visuel méthode Rissala pour débutants."',
   'description: "Understand harakāt: fatha, kasra, damma, and sukun. Short vowels in Arabic are NOT letters. Visual Rissala method guide for beginners."'],
  ['prevArticleTitle: "Les 4 formes des lettres"', 'prevArticleTitle: "The 4 forms of letters"'],
  ['nextArticleTitle: "Les voyelles longues"', 'nextArticleTitle: "Long vowels"'],
  ['Vous connaissez maintenant les **28 lettres arabes** et leurs **4 formes contextuelles**. Mais il manque un élément crucial : comment prononce-t-on ces lettres ? Comment sait-on si',
   'You now know the **28 Arabic letters** and their **4 contextual forms**. But a crucial element is missing: how do you pronounce these letters? How do you know if'],
  ['se prononce « ba », « bi » ou « bu » ?', 'is pronounced "ba," "bi," or "bu"?'],
  ["La réponse : les **voyelles courtes**, appelées **harakāt** (حَرَكَات) en arabe. Et c'est ici que l'arabe révèle sa logique la plus fascinante.",
   'The answer: **short vowels**, called **harakāt** (حَرَكَات) in Arabic. And this is where Arabic reveals its most fascinating logic.'],
  ['## Le concept fondamental : les voyelles courtes ne sont PAS des lettres', '## The fundamental concept: short vowels are NOT letters'],
  ["C'est **le point le plus important** de cet article.", 'This is **the most important point** in this article.'],
  ['En français, les voyelles (a, e, i, o, u) sont des lettres à part entière, inscrites dans les mots. En arabe, les voyelles courtes sont des **signes diacritiques** — de petits symboles ajoutés au-dessus ou en dessous des consonnes.',
   'In French, vowels (a, e, i, o, u) are full letters written in words. In Arabic, short vowels are **diacritical marks** — small symbols added above or below consonants.'],
  ["Elles ne font pas partie du « squelette » du mot. Elles sont comme des annotations que l'on peut ajouter ou retirer sans changer l'écriture de base.",
   'They are not part of the word\'s "skeleton." They are like annotations that can be added or removed without changing the basic writing.'],
  ['### 💡 Analogie Rissala', '### 💡 Rissala analogy'],
  ["Pensez aux consonnes comme au **squelette** d'un mot, et aux voyelles courtes comme à la **chair** qui l'entoure. Le squelette est toujours écrit. La chair est souvent implicite — le lecteur expérimenté la reconstitue mentalement.",
   'Think of consonants as the **skeleton** of a word, and short vowels as the **flesh** around it. The skeleton is always written. The flesh is often implicit — the experienced reader reconstructs it mentally.'],
  ['## Les 3 voyelles courtes + le sukun', '## The 3 short vowels + sukun'],
  ["L'arabe n'a que **3 voyelles courtes**. C'est remarquablement simple comparé au français (qui en a une quinzaine de sons vocaliques). Plus un signe spécial, le sukun, qui indique l'absence de voyelle.",
   'Arabic has only **3 short vowels**. That is remarkably simple compared to French (which has about fifteen vowel sounds). Plus a special sign, sukun, indicating the absence of a vowel.'],
  ['<th>Nom</th>', '<th>Name</th>'], ['<th>Signe</th>', '<th>Sign</th>'], ['<th>Son</th>', '<th>Sound</th>'],
  ['<th>Exemple</th>', '<th>Example</th>'], ['<th>Prononciation</th>', '<th>Pronunciation</th>'],
  ['Au-dessus', 'Above'], ['En dessous', 'Below'], ['a (bref)', 'a (short)'], ['i (bref)', 'i (short)'],
  ['u (bref, ou)', 'u (short, oo)'], ['∅ (aucun)', '∅ (none)'], ['b (consonne seule)', 'b (consonant only)'],
  ['## La Fatha : le son « a »', '## Fatha: the "a" sound'],
  ['La **fatha** (فَتْحَة) est un petit trait oblique placé **au-dessus** de la consonne. Elle lui donne le son « a » bref.',
   '**Fatha** (فَتْحَة) is a small slanted stroke placed **above** the consonant. It gives it the short "a" sound.'],
  ['La fatha est la voyelle la plus fréquente en arabe. Elle correspond au son « a » bref et ouvert. La lettre seule',
   'Fatha is the most frequent vowel in Arabic. It corresponds to the short, open "a" sound. The letter alone'],
  ['est muette. Avec la fatha', 'is silent. With fatha'], [', elle devient « ba ».', ', it becomes "ba."'],
  ['## La Kasra : le son « i »', '## Kasra: the "i" sound'],
  ['La **kasra** (كَسْرَة) est un petit trait oblique placé **en dessous** de la consonne. Elle lui donne le son « i » bref.',
   '**Kasra** (كَسْرَة) is a small slanted stroke placed **below** the consonant. It gives it the short "i" sound.'],
  ['La position est logique : la fatha est **au-dessus** (ouverte, « a »), la kasra est **en dessous** (fermée, « i »). Cette symétrie visuelle aide à la mémorisation.',
   'The position is logical: fatha is **above** (open, "a"), kasra is **below** (closed, "i"). This visual symmetry aids memorization.'],
  ['## La Damma : le son « u » (ou)', '## Damma: the "u" (oo) sound'],
  ['La **damma** (ضَمَّة) est un petit « waw » miniature', '**Damma** (ضَمَّة) is a miniature "waw"'],
  ['placé **au-dessus** de la consonne. Elle lui donne le son « ou » bref (transcrit « u »).',
   'placed **above** the consonant. It gives it the short "oo" sound (transcribed "u").'],
  ["## Le Sukun : l'absence de voyelle", '## Sukun: absence of vowel'],
  ["Le **sukun** (سُكُون) est un petit cercle placé au-dessus de la consonne. Il indique que la consonne n'est suivie d'aucune voyelle — elle est « muette ».",
   '**Sukun** (سُكُون) is a small circle placed above the consonant. It indicates the consonant is not followed by any vowel — it is "silent."'],
  ['Par exemple, dans le mot <span class="arabic-inline">بَيْت</span> (bayt, « maison »), le',
   'For example, in the word <span class="arabic-inline">بَيْت</span> (bayt, "house"), the'],
  ["porte un sukun : le yā' ne se prononce pas « ya » ni « yi » ni « yu », mais simplement « y » (comme dans « bayt »).",
   'carries sukun: the yā\' is not pronounced "ya," "yi," or "yu," but simply "y" (as in "bayt").'],
  ['### 📌 Résumé visuel', '### 📌 Visual summary'],
  ['= trait au-dessus = « a » | **Kasra** (ـِ) = trait en dessous = « i » | **Damma** (ـُ) = boucle au-dessus = « u/ou » | **Sukun** (ـْ) = cercle au-dessus = silence',
   '= stroke above = "a" | **Kasra** (ـِ) = stroke below = "i" | **Damma** (ـُ) = loop above = "u/oo" | **Sukun** (ـْ) = circle above = silence'],
  ['## Pourquoi les voyelles courtes sont souvent absentes', '## Why short vowels are often absent'],
  ['Dans la vie quotidienne — journaux, livres, sites internet, panneaux — les voyelles courtes **ne sont pas écrites**.',
   'In everyday life — newspapers, books, websites, signs — short vowels **are not written**.'],
  ["L'arabe s'écrit principalement avec le squelette consonantique, et le lecteur reconstitue les voyelles grâce à :",
   'Arabic is written mainly with the consonantal skeleton, and the reader reconstructs vowels through:'],
  ['Le **contexte** de la phrase', 'The **context** of the sentence'],
  ['Sa **connaissance du vocabulaire**', 'Their **knowledge of vocabulary**'],
  ['Les **patterns morphologiques** de la langue', 'The language\'s **morphological patterns**'],
  ['Les voyelles courtes sont écrites dans seulement 3 contextes :', 'Short vowels are written in only 3 contexts:'],
  ['**Le Coran** — pour garantir une lecture parfaite', '**The Quran** — to ensure perfect recitation'],
  ["**Les manuels pour débutants** — pour faciliter l'apprentissage", '**Beginner textbooks** — to facilitate learning'],
  ['**Les textes ambigus** — quand le contexte ne suffit pas', '**Ambiguous texts** — when context is not enough'],
  ['## Les consonnes sans voyelles = le squelette du mot', '## Consonants without vowels = the skeleton of the word'],
  ['Pour bien comprendre, regardons le mot « kataba » (il a écrit) sous trois formes :',
   'To understand clearly, let us look at the word "kataba" (he wrote) in three forms:'],
  ['Avec toutes les voyelles', 'With all vowels'],
  ['Sans voyelles (texte normal)', 'Without vowels (normal text)'],
  ['Autre vocalisation', 'Other vocalization'],
  ['Remarquez : les mêmes consonnes', 'Notice: the same consonants'],
  ['produisent des mots différents selon les voyelles : **kataba** (il a écrit) vs **kutub** (livres). Le squelette consonantique est le même — ce sont les voyelles qui changent le sens.',
   'produce different words depending on vowels: **kataba** (he wrote) vs **kutub** (books). The consonantal skeleton is the same — it is the vowels that change the meaning.'],
  ['### ⚠️ Point critique', '### ⚠️ Critical point'],
  ["C'est pour cela que les voyelles courtes sont si importantes pour le débutant. Sans elles, le mot",
   'That is why short vowels are so important for beginners. Without them, the word'],
  ['pourrait se lire kataba, kutub, kutib, kātib... C\'est le contexte (et plus tard, votre vocabulaire) qui vous guidera.',
   'could be read kataba, kutub, kutib, kātib... Context (and later, your vocabulary) will guide you.'],
  ['## Le tanwīn : la double voyelle', '## Tanwīn: the double vowel'],
  ['Le **tanwīn** (تَنْوِين) est un doublement de la voyelle courte qui ajoute un son « n » à la fin. Il existe trois formes :',
   '**Tanwīn** (تَنْوِين) is a doubling of the short vowel that adds an "n" sound at the end. There are three forms:'],
  ["Le tanwīn est un concept grammatical (lié aux cas de déclinaison). Ne vous y attardez pas maintenant — retenez simplement qu'il existe et que c'est un « doublement + n ».",
   'Tanwīn is a grammatical concept (related to declension). Do not dwell on it now — simply remember it exists and is a "doubling + n."'],
  ['## Exercice de lecture avec harakāt', '## Reading exercise with harakāt'],
  ['Lisez ces syllabes en appliquant les voyelles courtes :', 'Read these syllables applying short vowels:'],
  ['1.  Les voyelles courtes (**harakāt**) sont des **diacritiques**, pas des lettres.',
   '1.  Short vowels (**harakāt**) are **diacritics**, not letters.'],
  ['3.  Dans les textes courants, les voyelles courtes sont **absentes**.',
   '3.  In everyday texts, short vowels are **absent**.'],
  ['4.  Les mêmes consonnes + voyelles différentes = **mots différents** (k-t-b → kataba, kutub...).',
   '4.  Same consonants + different vowels = **different words** (k-t-b → kataba, kutub...).'],
  ['5.  Le Coran et les manuels pour débutants incluent les voyelles pour faciliter la lecture.',
   '5.  The Quran and beginner textbooks include vowels to facilitate reading.'],
  ["L'article suivant aborde les **voyelles longues** — des lettres à part entière qui, contrairement aux harakāt, font partie intégrante du squelette du mot.",
   'The next article covers **long vowels** — full letters that, unlike harakāt, are an integral part of the word skeleton.'],
];

const vlEn = [
  ['title: "Voyelles Longues en Arabe"', 'title: "Long Vowels in Arabic"'],
  ['titleAccent: "Les Vraies Lettres Vocaliques"', 'titleAccent: "The True Vocalic Letters"'],
  ['subtitle: "Contrairement aux voyelles courtes (diacritiques), les voyelles longues sont de vraies lettres écrites dans le mot."',
   'subtitle: "Unlike short vowels (diacritics), long vowels are real letters written in the word."'],
  ['description: "Les voyelles longues en arabe (ا و ي) sont de vraies lettres, pas des diacritiques. Comprenez la différence entre voyelles courtes et longues. Guide Rissala."',
   'description: "Long vowels in Arabic (ا و ي) are real letters, not diacritics. Understand the difference between short and long vowels. Rissala guide."'],
  ['prevArticleTitle: "Les voyelles courtes"', 'prevArticleTitle: "Short vowels"'],
  ['nextArticleTitle: "Méthode Rissala : plan 30 jours"', 'nextArticleTitle: "Rissala method: 30-day plan"'],
  ["Dans l'article précédent, vous avez appris que les voyelles courtes (**harakāt**) sont des diacritiques — de petits signes au-dessus ou en dessous des consonnes. Elles sont souvent absentes dans les textes courants.",
   'In the previous article, you learned that short vowels (**harakāt**) are diacritics — small signs above or below consonants. They are often absent in everyday texts.'],
  ['Les **voyelles longues**, elles, sont fondamentalement différentes. Ce sont de **vraies lettres**, inscrites dans le mot, qui font partie du squelette consonantique. Elles ne disparaissent jamais. Elles sont toujours écrites.',
   '**Long vowels**, on the other hand, are fundamentally different. They are **real letters**, written in the word, part of the consonantal skeleton. They never disappear. They are always written.'],
  ['## La distinction fondamentale : diacritique vs lettre', '## The fundamental distinction: diacritic vs letter'],
  ["C'est le concept le plus important à maîtriser à ce stade de votre apprentissage. Résumons :",
   'This is the most important concept to master at this stage of your learning. Let us summarize:'],
  ['<th>Propriété</th>', '<th>Property</th>'],
  ['<th>Voyelles courtes (harakāt)</th>', '<th>Short vowels (harakāt)</th>'],
  ['<th>Voyelles longues</th>', '<th>Long vowels</th>'],
  ['Diacritiques (signes ajoutés)', 'Diacritics (added signs)'],
  ['Lettres à part entière', 'Full letters'],
  ['Souvent omises dans les textes', 'Often omitted in texts'],
  ['Toujours écrites', 'Always written'],
  ['Durée du son', 'Sound duration'],
  ['Bref (~1 temps)', 'Short (~1 beat)'],
  ['Long (~2 temps)', 'Long (~2 beats)'],
  ['Nombre', 'Number'],
  ['Lettres', 'Letters'],
  ['### 💡 Concept clé', '### 💡 Key concept'],
  ["Les voyelles courtes sont comme des **accents** qu'on peut omettre. Les voyelles longues sont comme des **lettres** qu'on ne peut jamais supprimer. Sans elles, le mot n'existe plus.",
   'Short vowels are like **accents** that can be omitted. Long vowels are like **letters** that can never be removed. Without them, the word no longer exists.'],
  ['## Les 3 voyelles longues', '## The 3 long vowels'],
  ["L'arabe n'a que **3 voyelles longues**. Chacune est une lettre que vous connaissez déjà :",
   'Arabic has only **3 long vowels**. Each is a letter you already know:'],
  ['<th>Sens</th>', '<th>Meaning</th>'],
  ['a long (~2 temps)', 'long a (~2 beats)'],
  ['ou long (~2 temps)', 'long oo (~2 beats)'],
  ['i long (~2 temps)', 'long i (~2 beats)'],
  ['### Alif (ا) — le « ā » long', '### Alif (ا) — long "ā"'],
  ["L'**Alif** est la première lettre de l'alphabet arabe. Quand elle joue le rôle de voyelle longue, elle prolonge le son « a ». Elle est précédée d'une consonne portant une fatha.",
   '**Alif** is the first letter of the Arabic alphabet. When it acts as a long vowel, it prolongs the "a" sound. It is preceded by a consonant carrying fatha.'],
  ['Mécanisme : **consonne + fatha + alif** = son « ā » prolongé.',
   'Mechanism: **consonant + fatha + alif** = prolonged "ā" sound.'],
  ['### Wāw (و) — le « ū » long', '### Wāw (و) — long "ū"'],
  ['Le **Wāw** comme voyelle longue prolonge le son « ou ». La consonne précédente porte une damma.',
   '**Wāw** as a long vowel prolongs the "oo" sound. The preceding consonant carries damma.'],
  ['Mécanisme : **consonne + damma + wāw** = son « ū » prolongé.',
   'Mechanism: **consonant + damma + wāw** = prolonged "ū" sound.'],
  ["### Yā' (ي) — le « ī » long", '### Yā\' (ي) — long "ī"'],
  ["Le **Yā'** comme voyelle longue prolonge le son « i ». La consonne précédente porte une kasra.",
   '**Yā\'** as a long vowel prolongs the "i" sound. The preceding consonant carries kasra.'],
  ["Mécanisme : **consonne + kasra + yā'** = son « ī » prolongé.",
   'Mechanism: **consonant + kasra + yā\'** = prolonged "ī" sound.'],
  ['## Voyelle courte vs voyelle longue : la différence change le sens',
   '## Short vowel vs long vowel: the difference changes meaning'],
  ["Ce n'est pas qu'une question de durée. En arabe, la longueur de la voyelle **change le sens du mot**. Confondre une voyelle courte et une voyelle longue peut créer un contresens total.",
   'It is not just a matter of duration. In Arabic, vowel length **changes the meaning of the word**. Confusing a short and long vowel can create a total misunderstanding.'],
  ['<th>Mot</th>', '<th>Word</th>'], ['<th>Transcription</th>', '<th>Transcription</th>'],
  ['<th>Voyelle</th>', '<th>Vowel</th>'],
  ['courtes uniquement', 'short only'], ['courtes (u, u)', 'short (u, u)'],
  ['il a correspondu avec', 'he corresponded with'],
  ['ā long (alif après kāf)', 'long ā (alif after kāf)'],
  ['ā long + i court', 'long ā + short i'],
  ['Regardez : les mêmes consonnes', 'Look: the same consonants'],
  ['(k-t-b, racine de « écrire ») produisent 4 mots totalement différents selon les voyelles (courtes et longues). C\'est la **magie du système de racines arabes**.',
   '(k-t-b, root of "write") produce 4 completely different words depending on vowels (short and long). This is the **magic of the Arabic root system**.'],
  ['### ⚠️ Erreur fréquente', '### ⚠️ Common mistake'],
  ['Ne confondez JAMAIS « ba » (بَ, fatha seule) avec « bā » (بَا, fatha + alif). Le premier est un son bref, le second est un son tenu. Cette distinction est **sémantiquement critique** en arabe.',
   'NEVER confuse "ba" (بَ, fatha alone) with "bā" (بَا, fatha + alif). The first is a short sound, the second is held. This distinction is **semantically critical** in Arabic.'],
  ['## Le mécanisme : voyelle courte + lettre longue', '## The mechanism: short vowel + long letter'],
  ['Les voyelles longues ne fonctionnent pas seules. Elles forment toujours un **couple** avec la voyelle courte correspondante sur la consonne qui les précède :',
   'Long vowels do not work alone. They always form a **pair** with the corresponding short vowel on the consonant that precedes them:'],
  ['<th>Voyelle courte</th>', '<th>Short vowel</th>'],
  ['<th>+ Lettre longue</th>', '<th>+ Long letter</th>'],
  ['<th>= Son long</th>', '<th>= Long sound</th>'],
  ['a prolongé', 'prolonged a'], ['ou prolongé', 'prolonged oo'], ['i prolongé', 'prolonged i'],
  ["C'est un système parfaitement logique. La voyelle courte « annonce » la voyelle longue qui suit. Fatha annonce Alif, Damma annonce Wāw, Kasra annonce Yā'.",
   'It is a perfectly logical system. The short vowel "announces" the long vowel that follows. Fatha announces Alif, Damma announces Wāw, Kasra announces Yā\'.'],
  ["## Wāw et Yā' : double rôle (consonne ou voyelle)", '## Wāw and Yā\': dual role (consonant or vowel)'],
  ['Attention :', 'Note:'],
  ['sont des lettres à **double fonction**. Elles peuvent être :',
   'are letters with a **dual function**. They can be:'],
  ['**Consonnes** : quand elles portent elles-mêmes une voyelle courte ou un sukun en début de syllabe',
   '**Consonants**: when they themselves carry a short vowel or sukun at the start of a syllable'],
  ['**Voyelles longues** : quand elles prolongent le son de la consonne précédente',
   '**Long vowels**: when they prolong the sound of the preceding consonant'],
  ['Exemple avec Wāw comme consonne :', 'Example with Wāw as consonant:'],
  ['(walad = enfant/garçon). Ici, le wāw porte une fatha — il se prononce « wa », c\'est une consonne.',
   '(walad = child/boy). Here, wāw carries fatha — it is pronounced "wa," a consonant.'],
  ['Exemple avec Wāw comme voyelle longue :', 'Example with Wāw as long vowel:'],
  ['(nūr = lumière). Ici, le wāw prolonge le « u » de la consonne nūn — c\'est une voyelle longue.',
   '(nūr = light). Here, wāw prolongs the "u" of nūn — it is a long vowel.'],
  ['## Exercice de distinction', '## Distinction exercise'],
  ['Identifiez si la voyelle soulignée est courte ou longue :', 'Identify whether the underlined vowel is short or long:'],
  ['Diphtongue (ay)', 'Diphthong (ay)'],
  ['Le yā\' porte sukun = semi-voyelle', 'Yā\' carries sukun = semi-vowel'],
  ['Voyelle longue ā', 'Long vowel ā'],
  ['Alif après fatha = ā prolongé', 'Alif after fatha = prolonged ā'],
  ['Voyelle longue ū', 'Long vowel ū'],
  ['Wāw après damma = ū prolongé', 'Wāw after damma = prolonged ū'],
  ['Voyelle longue ī', 'Long vowel ī'],
  ["Yā' après kasra = ī prolongé", 'Yā\' after kasra = prolonged ī'],
  ['1.  Les voyelles longues sont de **vraies lettres**', '1.  Long vowels are **real letters**'],
  ['2.  Elles sont **toujours écrites**, contrairement aux voyelles courtes.',
   '2.  They are **always written**, unlike short vowels.'],
  ['3.  Chaque voyelle longue est **précédée de sa voyelle courte correspondante**.',
   '3.  Each long vowel is **preceded by its corresponding short vowel**.'],
  ['4.  La longueur de la voyelle **change le sens** du mot (kataba ≠ kātaba).',
   '4.  Vowel length **changes the meaning** of the word (kataba ≠ kātaba).'],
  ['5.  Wāw et Yā\' ont un **double rôle** : consonne ou voyelle longue selon le contexte.',
   '5.  Wāw and Yā\' have a **dual role**: consonant or long vowel depending on context.'],
  ["Vous maîtrisez maintenant l'alphabet complet, les formes contextuelles, les voyelles courtes et les voyelles longues. Dans l'article final, nous assemblons tout cela dans la **méthode Rissala : un plan de 30 jours** pour apprendre à lire l'arabe.",
   'You now master the full alphabet, contextual forms, short vowels, and long vowels. In the final article, we assemble everything into the **Rissala method: a 30-day plan** to learn to read Arabic.'],
];

// Process EN files
for (const [file, extra] of [
  ['voyelles-courtes-arabe.md', vcEn],
  ['voyelles-longues-arabe.md', vlEn],
]) {
  const p = path.join(enDir, file);
  let t = fs.readFileSync(p, 'utf8');
  t = rep(t, [...commonEn, ...extra]);
  fs.writeFileSync(p, t);
  console.log('EN done:', file);
}

const methodeEn = [
  ['Alphabet visuel', 'Visual alphabet'],
  ['Reconnaître les 28 lettres en forme isolée', 'Recognize the 28 letters in isolated form'],
  ['Formes contextuelles', 'Contextual forms'],
  ['Comprendre les 4 formes et les connexions', 'Understand the 4 forms and connections'],
  ['Voyelles courtes', 'Short vowels'],
  ['Maîtriser fatha, kasra, damma, sukun', 'Master fatha, kasra, damma, sukun'],
  ['Voyelles longues', 'Long vowels'],
  ["Distinguer alif (ā), wāw (ū), yā' (ī)", "Distinguish alif (ā), wāw (ū), yā' (ī)"],
  ['Lecture de mots', 'Word reading'],
  ['Lire des mots simples avec harakāt', 'Read simple words with harakāt'],
  ['Lecture sans harakāt', 'Reading without harakāt'],
  ['Lire un texte réel sans diacritiques', 'Read real text without diacritics'],
  ["Chaque étape s'appuie sur la précédente. Vous ne passez à l'étape suivante que lorsque la précédente est **solide**. C'est le principe de progression sans saut conceptuel.",
   'Each step builds on the previous one. You move to the next step only when the previous one is **solid**. This is the principle of progression without conceptual leaps.'],
  ['## La répétition espacée : le secret de la mémorisation', '## Spaced repetition: the secret of memorization'],
  ['La **répétition espacée** est le mécanisme de mémorisation le plus efficace validé par les neurosciences. Le principe est simple :',
   '**Spaced repetition** is the most effective memorization mechanism validated by neuroscience. The principle is simple:'],
  ['Vous apprenez une information (ex: la lettre', 'You learn a piece of information (e.g., the letter'],
  ['Vous la révisez **le lendemain**', 'You review it **the next day**'],
  ['Puis **3 jours après**', 'Then **3 days later**'],
  ['Puis **1 semaine après**', 'Then **1 week later**'],
  ['Puis **2 semaines après**', 'Then **2 weeks later**'],
  ["À chaque révision, l'information s'ancre plus profondément dans votre mémoire à long terme. Si vous révisez trop tôt, c'est du temps perdu. Trop tard, vous avez oublié. Le plan de 30 jours ci-dessous intègre ce rythme naturellement.",
   'With each review, the information anchors more deeply in your long-term memory. Review too early, and time is wasted. Too late, and you have forgotten. The 30-day plan below integrates this rhythm naturally.'],
  ['### 💡 Règle Rissala : 20 minutes par jour', '### 💡 Rissala rule: 20 minutes per day'],
  ["La méthode ne demande que **20 minutes par jour**, mais elles doivent être **quotidiennes**. 20 min × 30 jours = 10 heures. C'est suffisant pour passer de zéro à la lecture de base. La régularité bat l'intensité.",
   'The method requires only **20 minutes per day**, but they must be **daily**. 20 min × 30 days = 10 hours. That is enough to go from zero to basic reading. Consistency beats intensity.'],
  ['## Plan de 30 jours : semaine par semaine', '## 30-day plan: week by week'],
  ["### Semaine 1 : L'alphabet visuel (Jours 1-7)", '### Week 1: Visual alphabet (Days 1-7)'],
  ['<th>Période</th><th>Contenu</th><th>Action concrète</th>', '<th>Period</th><th>Content</th><th>Concrete action</th>'],
  ['Lettres ا à ذ (9 lettres) en forme isolée. Familles visuelles 1-3.', 'Letters ا to ذ (9 letters) in isolated form. Visual families 1-3.'],
  ['Voir chaque lettre, dire son nom, écrire 5 fois à la main.', 'See each letter, say its name, write it 5 times by hand.'],
  ['Lettres ر à ظ (9 lettres). Familles visuelles 4-6.', 'Letters ر to ظ (9 letters). Visual families 4-6.'],
  ['Révision des lettres J1-J2 + nouvelles lettres. Écriture.', 'Review letters D1-D2 + new letters. Writing.'],
  ['Lettres ع à ي (10 lettres). Familles visuelles 7+.', 'Letters ع to ي (10 letters). Visual families 7+.'],
  ['Révision J1-J4 + nouvelles lettres. Focus sur les 8 lettres difficiles.', 'Review D1-D4 + new letters. Focus on the 8 difficult letters.'],
  ['Révision complète des 28 lettres.', 'Complete review of all 28 letters.'],
  ['Test : couvrir les noms, regarder la lettre, la nommer et donner son son.', 'Test: cover the names, look at the letter, name it and give its sound.'],
  ['### Semaine 2 : Les formes contextuelles (Jours 8-14)', '### Week 2: Contextual forms (Days 8-14)'],
  ['Comprendre les 4 formes (isolée, initiale, médiane, finale).', 'Understand the 4 forms (isolated, initial, medial, final).'],
  ['Étudier le tableau des formes. Identifier les formes dans des mots simples.', 'Study the forms table. Identify forms in simple words.'],
  ['Les 6 lettres non-connectantes (ا د ذ ر ز و).', 'The 6 non-connecting letters (ا د ذ ر ز و).'],
  ['Exercices de décomposition de mots : identifier quelle forme est utilisée.', 'Word breakdown exercises: identify which form is used.'],
  ['Lecture de mots simples avec formes connectées.', 'Reading simple words with connected forms.'],
  ['Lire 20 mots simples en décomposant chaque lettre et sa forme.', 'Read 20 simple words breaking down each letter and its form.'],
  ['Révision semaines 1 + 2.', 'Review weeks 1 + 2.'],
  ["Relire l'intégralité des tableaux. Test de reconnaissance rapide.", 'Reread all tables. Quick recognition test.'],
  ['### Semaine 3 : Les voyelles (Jours 15-21)', '### Week 3: Vowels (Days 15-21)'],
  ['Voyelles courtes : fatha, kasra, damma, sukun.', 'Short vowels: fatha, kasra, damma, sukun.'],
  ['Lire des syllabes : بَ بِ بُ بْ pour chaque consonne.', 'Read syllables: بَ بِ بُ بْ for each consonant.'],
  ["Voyelles longues : alif (ā), wāw (ū), yā' (ī).", "Long vowels: alif (ā), wāw (ū), yā' (ī)."],
  ['Distinguer kataba/kātaba. Lire des mots avec voyelles longues.', 'Distinguish kataba/kātaba. Read words with long vowels.'],
  ['Combinaison voyelles courtes + longues dans des mots réels.', 'Combining short + long vowels in real words.'],
  ['Lire 30 mots du Coran avec harakāt. Identifier chaque voyelle.', 'Read 30 Quranic words with harakāt. Identify each vowel.'],
  ['Révision semaines 1-3.', 'Review weeks 1-3.'],
  ['Lire une page du Coran avec harakāt, lentement mais correctement.', 'Read a page of the Quran with harakāt, slowly but correctly.'],
  ['### Semaine 4 : Lecture progressive (Jours 22-30)', '### Week 4: Progressive reading (Days 22-30)'],
  ['Lecture de mots courants sans harakāt.', 'Reading common words without harakāt.'],
  ['Liste de 50 mots fréquents. Deviner la vocalisation par le contexte.', 'List of 50 frequent words. Guess vocalization from context.'],
  ['Lecture de phrases simples.', 'Reading simple sentences.'],
  ['Phrases courtes du Coran et du quotidien. Lecture fluide.', 'Short sentences from the Quran and daily life. Fluent reading.'],
  ["Lecture d'un paragraphe complet.", 'Reading a full paragraph.'],
  ['Texte court avec et sans harakāt. Comparer votre lecture.', 'Short text with and without harakāt. Compare your reading.'],
  ['Évaluation finale.', 'Final assessment.'],
  ['Lire la Fatiha sans aide. Lire un panneau en arabe. Auto-évaluation.', 'Read Al-Fatiha without help. Read an Arabic sign. Self-assessment.'],
  ['## Les 8 erreurs classiques des débutants en arabe', '## The 8 classic mistakes of Arabic beginners'],
  ["En 10+ ans d'enseignement, ces erreurs reviennent systématiquement. Évitez-les et vous gagnerez des semaines.",
   'In 10+ years of teaching, these mistakes come up systematically. Avoid them and you will save weeks.'],
  ["Apprendre l'alphabet dans l'ordre latin", 'Learning the alphabet in Latin order'],
  ["L'ordre alphabétique arabe n'a rien à voir avec le latin. Apprenez par familles visuelles, pas par correspondance A=Alif, B=Bā'.",
   'The Arabic alphabetical order has nothing to do with Latin. Learn by visual families, not by A=Alif, B=Bā\' correspondence.'],
  ['Mélanger alphabet et grammaire', 'Mixing alphabet and grammar'],
  ["La grammaire arabe est riche et complexe. L'introduire trop tôt surcharge le débutant. Alphabet d'abord, grammaire ensuite — jamais en parallèle au début.",
   'Arabic grammar is rich and complex. Introducing it too early overloads beginners. Alphabet first, grammar later — never in parallel at the start.'],
  ['Négliger les formes contextuelles', 'Neglecting contextual forms'],
  ["Beaucoup de cours enseignent uniquement la forme isolée. Résultat : l'apprenant ne reconnaît pas les lettres dans un texte réel. Les 4 formes sont essentielles.",
   'Many courses teach only the isolated form. Result: the learner cannot recognize letters in real text. The 4 forms are essential.'],
  ['Confondre voyelles courtes et longues', 'Confusing short and long vowels'],
  ["C'est l'erreur la plus courante. Les voyelles courtes sont des diacritiques, les longues sont des lettres. Les confondre change le sens des mots.",
   'This is the most common mistake. Short vowels are diacritics, long ones are letters. Confusing them changes word meanings.'],
  ['Vouloir prononcer parfaitement dès le début', 'Wanting perfect pronunciation from the start'],
  ["La prononciation du ع, ح, خ, ق s'affine avec le temps et l'écoute. Bloquer dessus au jour 1 est contre-productif. Avancez, la prononciation suivra.",
   'Pronunciation of ع, ح, خ, ق improves with time and listening. Getting stuck on day 1 is counterproductive. Move forward; pronunciation will follow.'],
  ['Ne pas écrire à la main', 'Not writing by hand'],
  ["L'écriture manuscrite active la mémoire musculaire. Taper au clavier ne remplace pas le geste d'écriture. Prenez un cahier et écrivez de droite à gauche.",
   'Handwriting activates muscle memory. Typing does not replace the writing gesture. Get a notebook and write from right to left.'],
  ['Sauter la phase « sans harakāt »', 'Skipping the "without harakāt" phase'],
  ["L'objectif final est de lire sans voyelles courtes. Si vous restez dépendant des harakāt, vous ne lirez jamais un journal, un livre ou un site web arabe.",
   'The final goal is reading without short vowels. If you stay dependent on harakāt, you will never read an Arabic newspaper, book, or website.'],
  ['Étudier de manière irrégulière', 'Studying irregularly'],
  ['20 minutes par jour pendant 30 jours > 5 heures une fois par semaine. La régularité est le facteur #1 de réussite. La répétition espacée ne fonctionne qu\'avec la constance.',
   '20 minutes per day for 30 days > 5 hours once a week. Consistency is the #1 success factor. Spaced repetition only works with constancy.'],
  ['## Les pièges de prononciation : les paires confuses', '## Pronunciation traps: confusing pairs'],
  ['Ces paires de lettres sont souvent confondues par les débutants francophones. Connaître ces pièges vous évitera des erreurs persistantes.',
   'These letter pairs are often confused by French-speaking beginners. Knowing these traps will save you from persistent errors.'],
  ['<th>Paire</th><th>Explication</th>', '<th>Pair</th><th>Explanation</th>'],
  ['Même forme, mais ح est un souffle (h profond) et خ est un frottement (kh). La différence est dans l\'intensité du son.',
   'Same shape, but ح is a breath (deep h) and خ is friction (kh). The difference is in sound intensity.'],
  ["ص est un 's' emphatique (lourd, bouche arrondie), س est un 's' léger (comme en français). Le contexte change le sens.",
   "ṣ is an emphatic 's' (heavy, rounded mouth), sīn is a light 's' (like in French). Context changes meaning."],
  ["ط est un 't' emphatique, ت est un 't' léger. L'emphase modifie toutes les voyelles environnantes.",
   "ṭ is an emphatic 't', tā' is a light 't'. Emphasis modifies all surrounding vowels."],
  ['ع est une contraction gutturale profonde, ء (hamza) est un coup de glotte léger. Deux sons radicalement différents.',
   "'Ayn is a deep guttural contraction, hamza (ء) is a light glottal stop. Two radically different sounds."],
  ["ض est un 'd' emphatique unique à l'arabe (l'arabe est parfois appelé « la langue du Ḍād »). د est un 'd' normal.",
   "Ḍād is a unique emphatic 'd' in Arabic (Arabic is sometimes called \"the language of Ḍād\"). Dāl is a normal 'd'."],
  ["ذ est un 'th' voisé (comme 'the' en anglais), ز est un 'z' pur. Beaucoup de dialectes fusionnent ces deux sons.",
   "Dhāl is a voiced 'th' (like English 'the'), zāy is a pure 'z'. Many dialects merge these two sounds."],
  ['## Après les 30 jours : et ensuite ?', '## After 30 days: what next?'],
  ['À la fin de ce plan, vous serez capable de :', 'At the end of this plan, you will be able to:'],
  ['**Reconnaître** les 28 lettres dans toutes leurs formes', '**Recognize** the 28 letters in all their forms'],
  ['**Lire** des mots arabes avec harakāt', '**Read** Arabic words with harakāt'],
  ['**Commencer** à lire sans harakāt (textes simples)', '**Begin** reading without harakāt (simple texts)'],
  ['**Distinguer** voyelles courtes et longues', '**Distinguish** short and long vowels'],
  ['**Écrire** des mots simples à la main', '**Write** simple words by hand'],
  ['La suite logique :', 'The logical next steps:'],
  ['**Vocabulaire thématique** — apprendre 500 mots fréquents', '**Thematic vocabulary** — learn 500 frequent words'],
  ['**Grammaire de base** — la phrase nominale, les pronoms, les démonstratifs', '**Basic grammar** — nominal sentence, pronouns, demonstratives'],
  ['**Lecture coranique** — lire le Coran avec tajwīd de base', '**Quranic reading** — read the Quran with basic tajwīd'],
  ['**Écoute active** — podcasts, vidéos, récitations pour affiner la prononciation', '**Active listening** — podcasts, videos, recitations to refine pronunciation'],
  ['### 🎯 La promesse Rissala', '### 🎯 The Rissala promise'],
  ["La méthode Rissala ne promet pas de miracles. Elle promet une **structure**. La plupart des gens abandonnent l'arabe non pas parce que c'est difficile, mais parce qu'ils n'ont **aucune feuille de route**. Vous avez maintenant la vôtre. Les 30 prochains jours ne dépendent que de votre **régularité**.",
   'The Rissala method does not promise miracles. It promises a **structure**. Most people give up Arabic not because it is hard, but because they have **no roadmap**. You now have yours. The next 30 days depend only on your **consistency**.'],
  ['## Résumé de la méthode Rissala', '## Summary of the Rissala method'],
  ['1.  Progression en **6 étapes** logiques, sans saut conceptuel.', '1.  Progression in **6 logical steps**, without conceptual leaps.'],
  ['2.  Mémorisation par **répétition espacée** et familles visuelles.', '2.  Memorization through **spaced repetition** and visual families.'],
  ['3.  **20 minutes par jour** pendant 30 jours = 10 heures de pratique structurée.', '3.  **20 minutes per day** for 30 days = 10 hours of structured practice.'],
  ['4.  Les **8 erreurs classiques** sont identifiées et évitées dès le départ.', '4.  The **8 classic mistakes** are identified and avoided from the start.'],
  ['5.  Les **pièges de prononciation** sont cartographiés pour les francophones.', '5.  **Pronunciation traps** are mapped for French speakers.'],
  ["6.  L'objectif final : **lire l'arabe sans harakāt** — comme un locuteur natif.", '6.  Final goal: **read Arabic without harakāt** — like a native speaker.'],
  ['Vous avez terminé les 5 articles de la série « Apprendre l\'Arabe — Méthode Rissala ». Vous disposez maintenant d\'une architecture complète d\'apprentissage. Il ne reste qu\'une chose : **commencer**.',
   'You have completed the 5 articles in the "Learn Arabic — Rissala Method" series. You now have a complete learning architecture. Only one thing remains: **begin**.'],
];

{
  const p = path.join(enDir, 'methode-rissala-30-jours.md');
  let t = fs.readFileSync(p, 'utf8');
  t = rep(t, [...commonEn, ...methodeEn]);
  fs.writeFileSync(p, t);
  console.log('EN done: methode-rissala-30-jours.md');
}

console.log('EN methode complete.');
