import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const arDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'content', 'ar', 'apprendre-arabe');

function rep(t, pairs) { for (const [a,b] of pairs) t = t.split(a).join(b); return t; }

const commonAr = [
  ['category: "langue-arabe"\n', ''],
  ['✓ Oui', '✓ سهل'],
  ['✗ Non', '✗ لا'],
  ['⚠ Difficile', '⚠ صعب'],
  ['## Résumé', '## الخلاصة'],
  ['maison', 'بيت'],
  ['stylo', 'قلم'],
  ['chaise', 'كرسي'],
  ['livre', 'كتاب'],
  ['porte', 'باب'],
  ['lumière', 'نور'],
  ['paix', 'سلام'],
  ['grand', 'كبير'],
  ['beau', 'جميل'],
  ['chemin', 'طريق'],
  ['âme/esprit', 'روح'],
  ['muraille', 'سور'],
];

const alphabetAr = [
  ['title: "Apprendre l\'Alphabet Arabe Facilement"', 'title: "تعلّم الأبجدية العربية بسهولة"'],
  ['titleAccent: "Méthode Rissala"', 'titleAccent: "منهج رسالة"'],
  ['subtitle: "Maîtrisez les 28 lettres arabes dans leur forme isolée. Zéro grammaire, 100% visuel."',
   'subtitle: "أتقن الحروف العربية الـ28 في شكلها المنفرد. بلا قواعد نحوية، تعلّم بصري بالكامل."'],
  ['description: "Apprenez les 28 lettres de l\'alphabet arabe avec la méthode Rissala : formes isolées, sons, direction d\'écriture et système abjad."',
   'description: "تعلّم الحروف الـ28 للأبجدية العربية بمنهج رسالة: الأشكال المنفردة، الأصوات، اتجاه الكتابة، ونظام الأبجد."'],
  ['nextArticleTitle: "Les 4 formes des lettres arabes"', 'nextArticleTitle: "أشكال الحروف العربية الأربعة"'],
  ['Vous voulez **apprendre l\'arabe**', 'تريد **تعلّم العربية**'],
  ["mais l'alphabet vous semble impossible", 'لكن الأبجدية تبدو مستحيلة'],
  ["C'est normal.", 'هذا طبيعي.'],
  ['La plupart des méthodes font une erreur fondamentale', 'أغلب المناهج ترتكب خطأً جوهرياً'],
  ['elles mélangent alphabet, grammaire et conjugaison dès le premier jour.', 'فتمزج الأبجدية والنحو والصرف من اليوم الأول.'],
  ['Résultat : surcharge cognitive et abandon.', 'النتيجة: عبء معرفي زائد ثم ترك التعلّم.'],
  ['La **méthode Rissala** prend le problème à l\'envers.', '**منهج رسالة** يعكس المشكلة.'],
  ['On commence par une seule chose', 'نبدأ بشيء واحد فقط'],
  ['**voir et reconnaître les 28 lettres arabes dans leur forme isolée**.', '**رؤية الحروف العربية الـ28 والتعرّف عليها في شكلها المنفرد**.'],
  ['Pas de grammaire. Pas de conjugaison.', 'بلا نحو. بلا صرف.'],
  ['Juste les lettres — leur forme, leur son, leur nom.', 'فقط الحروف — شكلها وصوتها واسمها.'],
  ["## Pourquoi l'alphabet arabe n'est PAS difficile", '## لماذا الأبجدية العربية ليست صعبة'],
  ["L'alphabet arabe contient **28 lettres**.", 'الأبجدية العربية تضم **28 حرفاً**.'],
  ["l'alphabet latin en a 26.", 'الأبجدية اللاتينية 26.'],
  ["Ce n'est pas le nombre qui pose problème", 'المشكلة ليست في العدد'],
  ['ce sont les formes inconnues', 'بل في الأشكال غير المألوفة'],
  ['Bonne nouvelle : beaucoup de lettres arabes **se ressemblent**.', 'خبر سار: كثير من الحروف العربية **تتشابه**.'],
  ['Elles partagent la même forme de base', 'تتشارك قاعدة شكلية واحدة'],
  ['ne se distinguent que par des **points diacritiques**', 'وتُميَّز فقط بـ**نقاط التشكيل**'],
  ['un point en dessous', 'نقطة تحت'],
  ['deux points au-dessus', 'نقطتان فوق'],
  ['trois points au-dessus', 'ثلاث نقاط فوق'],
  ['Même forme, juste des points différents.', 'نفس الشكل، نقاط مختلفة فقط.'],
  ['Si vous apprenez une lettre, vous en apprenez trois.', 'إذا تعلّمت حرفاً واحداً، تعلّمت ثلاثة.'],
  ['Ce principe de **regroupement par familles visuelles**', 'مبدأ **التجميع في عائلات بصرية**'],
  ['est au cœur de la méthode Rissala.', 'هو جوهر منهج رسالة.'],
  ['## Comprendre le système Abjad : l\'écriture consonantique', '## فهم نظام الأبجد: الكتابة بالحروف الساكنة'],
  ["L'arabe est un **abjad**", 'العربية **أبجدية**'],
  ['pas un alphabet au sens européen.', 'وليست أبجدية بالمعنى الأوروبي.'],
  ['on n\'écrit que les consonnes et les voyelles longues', 'نكتب الحروف الساكنة والحركات الطويلة فقط'],
  ['Les voyelles courtes', 'الحركات القصيرة'],
  ['ne sont pas écrites dans le texte courant', 'لا تُكتب في النص العادي'],
  ['elles sont « devinées » par le lecteur grâce au contexte.', 'فيستنتجها القارئ من السياق.'],
  ['### 💡 Concept clé : l\'Abjad', '### 💡 مفهوم أساسي: الأبجد'],
  ['Imaginez le français sans voyelles courtes', 'تخيّل الفرنسية بلا حركات قصيرة'],
  ['« les livres sont sur la table »', '« les livres sont sur la table »'],
  ['Votre cerveau reconstitue les voyelles manquantes.', 'دماغك يعيد بناء الحركات الناقصة.'],
  ["L'arabe fonctionne exactement de la même manière.", 'العربية تعمل بنفس الطريقة تماماً.'],
  ['Les 28 lettres sont les **briques de base**', 'الحروف الـ28 هي **لبنات النظام**'],
  ['de ce système.', 'الأساسية.'],
  ['Les voyelles courtes existent — on les appelle **harakāt**.', 'الحركات القصيرة موجودة — تُسمى **الحركات**.'],
  ['Ce sont de petits signes au-dessus ou en dessous des lettres.', 'علامات صغيرة فوق الحروف أو تحتها.'],
  ['Mais elles ne sont écrites que dans les textes d\'apprentissage, le Coran et les livres pour enfants.',
   'لكنها تُكتب في نصوص التعلّم والقرآن وكتب الأطفال فقط.'],
  ["## L'écriture de droite à gauche", '## الكتابة من اليمين إلى اليسار'],
  ["L'arabe s'écrit et se lit **de droite à gauche**.", 'العربية تُكتب وتُقرأ **من اليمين إلى اليسار**.'],
  ['Plus vous commencez tôt, plus le réflexe devient naturel.', 'كلما بدأت مبكراً، أصبحت العادة طبيعية.'],
  ['« kitāb » (livre) — se lit :', '« kitāb » (كتاب) — تُقرأ:'],
  ['## Les 28 lettres : tableau complet en forme isolée', '## الحروف الـ28: جدول كامل بالشكل المنفرد'],
  ['Chaque lettre est présentée dans sa **forme isolée**', 'يُعرض كل حرف في **شكله المنفرد**'],
  ["C'est la première chose à mémoriser.", 'وهذا أول ما يجب حفظه.'],
  ['<th>Lettre</th>', '<th>الحرف</th>'],
  ['<th>Nom</th>', '<th>الاسم</th>'],
  ['<th>Son</th>', '<th>الصوت</th>'],
  ['<th>Niveau</th>', '<th>المستوى</th>'],
  ['voyelle longue', 'حركة طويلة'],
  ['✓ Accessible', '✓ سهل'],
  ['### 📌 Conseil Rissala', '### 📌 نصيحة من منهج رسالة'],
  ['Ne mémorisez pas les 28 lettres en une seule session.', 'لا تحفظ الـ28 حرفاً في جلسة واحدة.'],
  ['La méthode recommande **5 à 7 lettres par jour**', 'المنهج يوصي بـ**5 إلى 7 حروف يومياً**'],
  ['avec révision de la veille.', 'مع مراجعة ما سبق.'],
  ['En 5 jours, vous connaissez tout l\'alphabet.', 'في 5 أيام تعرف الأبجدية كاملة.'],
  ['La clé : **répétition espacée**.', 'المفتاح: **التكرار المتباعد**.'],
  ['## Les familles visuelles : regrouper pour mémoriser', '## العائلات البصرية: التجميع للحفظ'],
  ['La méthode Rissala organise les lettres en **familles de formes similaires**.',
   'منهج رسالة ينظّم الحروف في **عائلات أشكال متشابهة**.'],
  ['Votre cerveau mémorise des patterns, pas des formes isolées sans lien.',
   'دماغك يحفظ أنماطاً، لا أشكالاً منفردة بلا صلة.'],
  ['### Famille 1 : ب ت ث ن ي — les « dents »', '### العائلة 1: ب ت ث ن ي — «الأسنان»'],
  ['Base en forme de barque avec des points qui les différencient.', 'قاعدة على شكل قارب ونقاط تميّزها.'],
  ['### Famille 2 : ج ح خ — les « crochets »', '### العائلة 2: ج ح خ — «الخطافات»'],
  ['Même forme en crochet arrondi.', 'نفس الشكل المنحني.'],
  ['point au centre', 'نقطة في الوسط'],
  ['aucun point', 'بلا نقطة'],
  ['point au-dessus', 'نقطة فوق'],
  ['### Famille 3 : د ذ — les « bâtons »', '### العائلة 3: د ذ — «العصي»'],
  ['Formes simples presque droites.', 'أشكال بسيطة شبه مستقيمة.'],
  ['se distingue par un point.', 'يُميَّز بنقطة.'],
  ['### Famille 4 : ر ز — les « têtes »', '### العائلة 4: ر ز — «الرؤوس»'],
  ['Petites formes courbes.', 'أشكال منحنية صغيرة.'],
  ['a un point au-dessus.', 'له نقطة فوق.'],
  ['### Famille 5 : س ش — les « dentures »', '### العائلة 5: س ش — «الأسنان الطويلة»'],
  ['Formes allongées.', 'أشكال ممدودة.'],
  ['a trois points au-dessus.', 'له ثلاث نقاط فوق.'],
  ['### Famille 6 : ص ض ط ظ — les « emphatiques »', '### العائلة 6: ص ض ط ظ — «المفخّمة»'],
  ['Lettres avec sons emphatiques prononcés avec plus de pression.', 'حروف مفخّمة تُنطق بضغط أكبر.'],
  ['### Famille 7 : ع غ — les « gutturales »', '### العائلة 7: ع غ — «الحلقية»'],
  ['Formes en nœud.', 'أشكال عقدية.'],
  ['sans point', 'بلا نقطة'],
  ['avec point', 'بنقطة'],
  ['## Les 8 lettres difficiles', '## الحروف الثمانية الصعبة'],
  ['Certaines lettres produisent des sons **sans équivalent en français**.',
   'بعض الحروف تُنتج أصواتاً **بلا مقابل في الفرنسية**.'],
  ["L'important est de les reconnaître visuellement d'abord.", 'المهم التعرّف عليها بصرياً أولاً.'],
  ['La prononciation s\'améliorera avec la pratique.', 'النطق يتحسّن بالممارسة.'],
  ['Contraction profonde du fond de la gorge.', 'انقباض عميق من أعماق الحلق.'],
  ['Aucun équivalent en français.', 'لا مقابل له في الفرنسية.'],
  ['Imaginez que vous comprimez votre gorge', 'تخيّل أنك تضغط حلقك'],
  ['pour produire un son grave.', 'لإخراج صوت عميق.'],
  ['Comme un « r » grasseyé très prononcé.', 'كحرف «r» مفخّم جداً.'],
  ['Proche du « r » français mais produit plus en arrière dans la gorge.',
   'قريب من «r» الفرنسية لكنه يُنتج أعمق في الحلق.'],
  ['Souffle chaud et profond depuis la gorge', 'نفَس حار عميق من الحلق'],
  ['comme souffler sur des lunettes pour les nettoyer, mais plus fort.',
   'كالنفخ على نظارة لتنظيفها، لكن بقوة أكبر.'],
  ['Comme la « jota » espagnole', 'كحرف «jota» الإسبانية'],
  ['ou le « ch » allemand dans « Bach ».', 'أو «ch» الألمانية في «Bach».'],
  ['Frottement d\'air dans l\'arrière-gorge.', 'احتكاك هواء في أعماق الحلق.'],
  ['Un « k » très profond', '«k» عميق جداً'],
  ['produit à la base de la langue contre la luette.', 'يُنتج من قاعدة اللسان عند اللهاة.'],
  ['Beaucoup plus en arrière qu\'un « k » normal.', 'أبعد بكثير من «k» العادي.'],
  ['Un « t » emphatique.', '«t» مفخّم.'],
  ['La langue touche le palais avec plus de pression', 'اللسان يلامس الحنك بضغط أكبر'],
  ['la bouche s\'arrondit. Son plus « lourd ».', 'والفم يتدوّر. صوت «أثقل».'],
  ['Version emphatique du « dh » (ذ).', 'نسخة مفخّمة من «dh» (ذ).'],
  ['Langue entre les dents avec emphase', 'اللسان بين الأسنان مع تفخيم'],
  ['son plus grave et rond.', 'صوت أعمق وأكثر استدارة.'],
  ['Un « s » emphatique.', '«s» مفخّم.'],
  ['La bouche prend une forme arrondie', 'الفم يأخذ شكلاً دائرياً'],
  ['le son est plus grave et plus « plein »', 'والصوت أعمق وأكثر «امتلاءً»'],
  ["qu'un « s » normal.", 'من «s» العادي.'],
  ['### ⚠️ Piège classique', '### ⚠️ فخ شائع'],
  ['Ne passez PAS des heures sur la prononciation', 'لا تقضِ ساعات في النطق'],
  ['avant de connaître toutes les lettres.', 'قبل معرفة كل الحروف.'],
  ['La méthode Rissala : **reconnaissance visuelle d\'abord**, prononciation ensuite. Avancez.',
   'منهج رسالة: **التعرّف البصري أولاً**، ثم النطق. تقدّم.'],
  ['## Comment mémoriser : la stratégie Rissala', '## كيف تحفظ: استراتيجية منهج رسالة'],
  ['### Étape 1 : Voir (reconnaissance visuelle)', '### الخطوة 1: الرؤية (التعرّف البصري)'],
  ['Regardez chaque lettre isolée.', 'انظر إلى كل حرف منفرد.'],
  ['votre cerveau dit « bā\' — son B ».', 'يقول دماغك «باء — صوت B».'],
  ['### Étape 2 : Comprendre (familles)', '### الخطوة 2: الفهم (العائلات)'],
  ['Regroupez par familles visuelles.', 'جمّع حسب العائلات البصرية.'],
  ['La compréhension renforce la mémoire.', 'الفهم يقوّي الذاكرة.'],
  ['### Étape 3 : Appliquer (écriture + répétition)', '### الخطوة 3: التطبيق (الكتابة والتكرار)'],
  ['Écrivez à la main, de droite à gauche.', 'اكتب يدوياً من اليمين إلى اليسار.'],
  ['La mémoire musculaire est puissante.', 'الذاكرة العضلية قوية.'],
  ['Révisez la veille avant d\'avancer.', 'راجع ما سبق قبل التقدّم.'],
  ["## Ce qu'on ne fait PAS encore", '## ما لا نفعله بعد'],
  ['**La grammaire** — elle viendra plus tard', '**النحو** — سيأتي لاحقاً'],
  ['**La conjugaison** — inutile tant que vous ne lisez pas', '**الصرف** — بلا جدوى قبل أن تقرأ'],
  ['**Les formes connectées** — article suivant', '**الأشكال المتصلة** — المقال التالي'],
  ['**Les voyelles courtes** — article 3', '**الحركات القصيرة** — المقال 3'],
  ['**La prononciation parfaite** — elle se développe avec le temps', '**النطق المثالي** — يتطوّر مع الوقت'],
  ['1.  L\'arabe a **28 lettres**, beaucoup se ressemblent (familles visuelles).',
   '1.  العربية لها **28 حرفاً**، كثير منها متشابه (عائلات بصرية).'],
  ["2.  L'arabe est un **abjad** : on écrit les consonnes, les voyelles courtes sont omises.",
   '2.  العربية **أبجدية**: نكتب الحروف الساكنة، والحركات القصيرة محذوفة.'],
  ["3.  L'écriture va de **droite à gauche**.", '3.  الكتابة من **اليمين إلى اليسار**.'],
  ['4.  Les lettres ont des **formes isolées** à mémoriser en premier.',
   '4.  للحروف **أشكال منفردة** تحفظ أولاً.'],
  ['5.  8 lettres ont des sons **sans équivalent en français**.',
   '5.  8 حروف لها أصوات **بلا مقابل في الفرنسية**.'],
  ['6.  Mémorisation : **voir → comprendre → appliquer**.',
   '6.  الحفظ: **رؤية ← فهم ← تطبيق**.'],
];

const formesAr = [
  ['title: "Les 4 Formes des Lettres Arabes"', 'title: "أشكال الحروف العربية الأربعة"'],
  ['titleAccent: "Isolée, Initiale, Médiane, Finale"', 'titleAccent: "منفرد، أولي، وسطي، نهائي"'],
  ['subtitle: "L\'arabe est un système graphique dynamique. Chaque lettre change de forme selon sa position dans le mot."',
   'subtitle: "العربية نظام كتابة ديناميكي. يتغيّر شكل كل حرف حسب موقعه في الكلمة."'],
  ['description: "Comprenez le système cursif arabe : chaque lettre change de forme selon sa position. Tableau complet des 4 formes + règles de connexion."',
   'description: "افهم نظام الكتابة العربية المتصلة: يتغيّر شكل كل حرف حسب موقعه. جدول كامل للأشكال الأربعة وقواعد الوصل."'],
  ['prevArticleTitle: "L\'alphabet arabe"', 'prevArticleTitle: "الأبجدية العربية"'],
  ['nextArticleTitle: "Les voyelles courtes"', 'nextArticleTitle: "الحركات القصيرة"'],
  ["Dans l'article précédent, vous avez appris à reconnaître les **28 lettres arabes dans leur forme isolée**. Maintenant, il faut comprendre un concept fondamental : en arabe, les lettres **changent de forme** selon leur position dans le mot.",
   'في المقال السابق، تعلّمت التعرّف على **الحروف العربية الـ28 في شكلها المنفرد**. والآن عليك فهم مفهوم أساسي: في العربية، **تتغيّر أشكال الحروف** حسب موقعها في الكلمة.'],
  ["Ce n'est pas un caprice graphique. C'est une conséquence directe du fait que l'arabe est une **écriture cursive** : les lettres se connectent entre elles, exactement comme en écriture manuscrite latine, mais **en permanence** — y compris en version imprimée.",
   'ليس هذا مجرّد اختيار جمالي. إنه نتيجة مباشرة لكون العربية **كتابة متصلة**: تتصل الحروف ببعضها، كالخط اليدوي اللاتيني، لكن **دائماً** — حتى في الطباعة.'],
  ['## Pourquoi les lettres arabes changent de forme', '## لماذا تتغيّر أشكال الحروف العربية'],
  ['## Résumé', '## الخلاصة'],
  ['## Les 6 lettres qui NE se connectent PAS à gauche', '## الحروف الستة التي لا تتصل جهة اليسار'],
  ['Dans l\'article suivant, nous abordons les **voyelles courtes (harakāt)**', 'في المقال التالي، نتناول **الحركات القصيرة (الحركات)**'],
];

const vcAr = [
  ['title: "Voyelles Courtes en Arabe"', 'title: "الحركات القصيرة في العربية"'],
  ['titleAccent: "La Lecture Invisible"', 'titleAccent: "القراءة الخفية"'],
  ['subtitle: "Les voyelles courtes (harakāt) ne sont PAS des lettres. Ce sont des signes diacritiques qui donnent vie aux consonnes."',
   'subtitle: "الحركات القصيرة (الحركات) ليست حروفاً. إنها علامات تشكيل تُحيي الحروف الساكنة."'],
  ['description: "Comprenez les harakāt : fatha, kasra, damma et sukun. Les voyelles courtes en arabe ne sont PAS des lettres. Guide visuel méthode Rissala pour débutants."',
   'description: "افهم الحركات: الفتحة والكسرة والضمة والسكون. الحركات القصيرة في العربية ليست حروفاً. دليل بصري من منهج رسالة للمبتدئين."'],
  ['prevArticleTitle: "Les 4 formes des lettres"', 'prevArticleTitle: "الأشكال الأربعة للحروف"'],
  ['nextArticleTitle: "Les voyelles longues"', 'nextArticleTitle: "الحركات الطويلة"'],
  ['## Le concept fondamental : les voyelles courtes ne sont PAS des lettres', '## المفهوم الأساسي: الحركات القصيرة ليست حروفاً'],
  ['## Résumé', '## الخلاصة'],
];

const vlAr = [
  ['title: "Voyelles Longues en Arabe"', 'title: "الحركات الطويلة في العربية"'],
  ['titleAccent: "Les Vraies Lettres Vocaliques"', 'titleAccent: "حروف العلة الحقيقية"'],
  ['subtitle: "Contrairement aux voyelles courtes (diacritiques), les voyelles longues sont de vraies lettres écrites dans le mot."',
   'subtitle: "على عكس الحركات القصيرة (علامات التشكيل)، الحركات الطويلة حروف حقيقية مكتوبة في الكلمة."'],
  ['description: "Les voyelles longues en arabe (ا و ي) sont de vraies lettres, pas des diacritiques. Comprenez la différence entre voyelles courtes et longues. Guide Rissala."',
   'description: "الحركات الطويلة في العربية (ا و ي) حروف حقيقية وليست علامات تشكيل. افهم الفرق بين الحركات القصيرة والطويلة. دليل رسالة."'],
  ['prevArticleTitle: "Les voyelles courtes"', 'prevArticleTitle: "الحركات القصيرة"'],
  ['nextArticleTitle: "Méthode Rissala : plan 30 jours"', 'nextArticleTitle: "منهج رسالة: خطة 30 يوماً"'],
  ['## Résumé', '## الخلاصة'],
];

const methodeAr = [
  ['title: "Méthode Rissala : Apprendre l\'Arabe"', 'title: "منهج رسالة: تعلّم العربية"'],
  ['titleAccent: "3x Plus Vite — Plan 30 Jours"', 'titleAccent: "أسرع 3 مرات — خطة 30 يوماً"'],
  ['subtitle: "Synthèse complète de la méthode Rissala. Plan structuré jour par jour, répétition espacée, erreurs à éviter."',
   'subtitle: "عرض شامل لمنهج رسالة. خطة يومية منظمة، تكرار متباعد، وأخطاء يجب تجنبها."'],
  ['description: "Plan structuré de 30 jours pour apprendre à lire l\'arabe : alphabet, formes, voyelles, lecture progressive. Méthode Rissala avec répétition espacée et erreurs à éviter."',
   'description: "خطة منظمة لـ30 يوماً لتعلّم قراءة العربية: الأبجدية، الأشكال، الحركات، قراءة تدريجية. منهج رسالة مع تكرار متباعد وأخطاء يجب تجنبها."'],
  ['prevArticleTitle: "Les voyelles longues"', 'prevArticleTitle: "الحركات الطويلة"'],
  ['## Résumé de la méthode Rissala', '## خلاصة منهج رسالة'],
  ['## Résumé', '## الخلاصة'],
];

for (const [file, extra] of [
  ['alphabet-arabe.md', alphabetAr],
  ['formes-lettres-arabes.md', formesAr],
  ['voyelles-courtes-arabe.md', vcAr],
  ['voyelles-longues-arabe.md', vlAr],
  ['methode-rissala-30-jours.md', methodeAr],
]) {
  const p = path.join(arDir, file);
  let t = fs.readFileSync(p, 'utf8');
  t = rep(t, [...commonAr, ...extra]);
  fs.writeFileSync(p, t);
  console.log('AR done:', file);
}

console.log('AR all files processed.');
